### ISSUE TITLE
Llamada a parse_sucursal dentro de parse_productos_y_precios

### ISSUE THREAD

**Issue by DiegoPiloni** [OpenDataCordoba/precios_claros#1]
Buenas, me tomé un rato de leer el código (no intenté ejecutar nada todavía). 

Es necesaria esta llamada a `parse_sucursal` dentro de `parse_productos_y_precios`?

https://github.com/OpenDataCordoba/precios_claros/blob/6cdff5aea759731f752980c788643cbee4214f7e/preciosclaros/spiders/pclaros.py#L165

Por lo que entendí del código la llamada a `parse_sucursal_first_page` se encarga de llamar tantas veces como sea necesario a `parse_sucursal`.

Se poco de scrapy así que capaz me estoy equivocando pero esto es lo que ví y me llamó la atención.

**Comment by mgaitan** [comment]
fixed en 07b8407
