### ISSUE TITLE
Generar datasets de esta semana

### ISSUE THREAD

**Issue by mgaitan** [OpenDataCordoba/precios_claros#3]
Necesitamos ayuda para bajar los datos.  

- Seguir las instrucciones de instalación del scraper del README
- Avisar qué porción (de las disponibles) vas a bajar en un comentario de este issue
- Ejecutar

```
$ scrapy crawl preciosclaros -a porcion=<porcion> -a exportar=1 -a max_sucursales_por_cadena=1 -a max_sucursales_criterio=provincia --loglevel=INFO --logfile=scrap.log
```
(en mi conexion lenta demora aproximadamente 1 hora)

Podes elegir varias porciones a bajar. 

- subir los archivos `.csv  en data/ y el `scrap.log` a un gist, drive o donde puedas, y pegá el link para bajarlo editando tu comentario anterior

Hasta que encontremos una manera mejor, esto lo vamos a hacer una vez cada algunos dias

### Porciones 

- [x] porcion 1/5
- [x] porcion 2/5
- [x] porcion 3/5
- [x] porcion 4/5
- [x] porcion 5/5

**Comment by DiegoPiloni** [comment]
Porción 2/5:
https://drive.google.com/open?id=1pirBnEKwzPyhgOEbCbdSadLuZqrAiL07

**Comment by DiegoPiloni** [comment]
Porción 3/5:
https://drive.google.com/open?id=16nN3olomqsaSRMfO1tSbLwiKvowtZ2Ir

**Comment by DiegoPiloni** [comment]
Bajando 4/5

**Comment by mgaitan** [comment]
groso Diego!

**Comment by pdelboca** [comment]
Estoy bajando la porcion 5/5

**Comment by DiegoPiloni** [comment]
Bajando 4/5

**Comment by mgaitan** [comment]
ya casi estamos!

**Comment by DiegoPiloni** [comment]
Están todos, no?

**Comment by mgaitan** [comment]
estamos si. en cuanto suban esos los mergeo y subo. Ya hay datasets de dos semanas para hacer analisis!

**Comment by DiegoPiloni** [comment]
Perdón pero no entendí si el 4/5 lo bajó alguien más. Yo había comentado "bajando" pero me fui a dormir y descomenté por si alguien más lo bajaba antes que yo. (Lo tengo bajado igual, asi que si no lo bajó nadie más lo comparto)

**Comment by mgaitan** [comment]
si, subilo porfa

**Comment by DiegoPiloni** [comment]
Porción 4/5:
https://drive.google.com/open?id=1wQ8K2Jg45ENC8Z_Kn-5D5DzOuaGgbOsX

**Comment by mgaitan** [comment]
@pdelboca ya bajé el 5/5 
subi todo acá 
https://www.kaggle.com/tinnqn/precios-claros-precios-de-argentina

**Comment by mgaitan** [comment]
armé un notebook de ejemplo acá 
https://www.kaggle.com/tinnqn/ejemplo-analisis-de-precios-abril

agradezco review y que hagas sus propias magias con los datos!
