### ISSUE TITLE
Datasets semana 3

### ISSUE THREAD

**Issue by mgaitan** [OpenDataCordoba/precios_claros#5]
Necesitamos ayuda para bajar los datos.  

- Seguir las instrucciones de instalación del scraper del README
- Avisar qué porción (de las disponibles) vas a bajar en un comentario de este issue
- Ejecutar

```
$ scrapy crawl preciosclaros -a porcion=<porcion> -a exportar=1 -a max_sucursales_por_cadena=1 -a max_sucursales_criterio=provincia --loglevel=INFO --logfile=scrap.log
```
(en mi conexion lenta demora aproximadamente 1 hora)

Podes elegir varias porciones a bajar. 

- subir los archivos `.csv  en data/ y el `scrap.log` a un gist, drive o donde puedas, y pegá el link para bajarlo editando tu comentario anterior

### Porciones 

- [x] porcion 1/5
- [x] porcion 2/5
- [x] porcion 3/5
- [x] porcion 4/5
- [x] porcion 5/5

**Comment by mgaitan** [comment]
@DiegoPiloni @pdelboca @pandres bajan alguna?

**Comment by mgaitan** [comment]
porfa, actualicen el codigo

**Comment by pdelboca** [comment]
bajando 5/5
